behaviors:
  testingAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024 # Pasos posibles a guardar para alimentar la red neuronal. A más alto más lento pero más estable.
      buffer_size: 10240 # Experiencias necesarias para modificar el modelo. Multiplo de batch_size.
      learning_rate: 0.0005 # Frecuencia de actualización de los pesos de la red neuronal. A más bajo, más estable, a más alto, más rápido.
      beta: 0.01 # Aleatoriedad de la pólítica al inicio del entrenamiento.
      epsilon: 0.2 # Porcentaje (tanto por uno) de cambio de la política en cada update.
      lambd: 0.90 # Imperatividad de las recompensas del estado actual.
      num_epoch: 3 # Estabilidad vs. rapidez del entrenamiento.
      learning_rate_schedule: constant
    network_settings:
      normalize: true # Indica si el vector de acciones se normaliza.
      hidden_units: 256 # Unidades que tienen cada una de las capas ocultas. A más complejo el sistema de acciones, más alto.
      num_layers: 2 # Capas ocultas en la red neuronal
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0
      gail:
        gamma: 0.99
        strength: 1.0
        demo_path: demo200326/demo34.demo
    behavioral_cloning:
      strength: 0
      steps: 500000
      demo_path: demo200326/demo34.demo
    keep_checkpoints: 5
    max_steps: 5000000 # Ciclos observación/acción/observación que el agente realiza antes de finalizar el entrenamiento.
    time_horizon: 128 # Predicción de recompensas
    summary_freq: 10000
    threaded: true
